//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoAdjunto
    {
        public ArchivoAdjunto()
        {
            this.ArchivoAccion = new HashSet<ArchivoAccion>();
            this.ArchivoCausa = new HashSet<ArchivoCausa>();
            this.FormatoPorCliente = new HashSet<FormatoPorCliente>();
        }
    
        public int ArchivoId { get; set; }
        public string Url { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<ArchivoAccion> ArchivoAccion { get; set; }
        public virtual ICollection<ArchivoCausa> ArchivoCausa { get; set; }
        public virtual ICollection<FormatoPorCliente> FormatoPorCliente { get; set; }
    }
}
