//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaPorCliente
    {
        public int DetalleId { get; set; }
        public int CategoriaId { get; set; }
        public int ClienteId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
