//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int EmailId { get; set; }
        public string EmailDe { get; set; }
        public string EmailPara { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public byte Enviado { get; set; }
    }
}
