//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormatoPorCliente
    {
        public int FormatoId { get; set; }
        public int ClienteId { get; set; }
        public int SubcategoriaId { get; set; }
        public Nullable<int> ArchivoId { get; set; }
        public string Nota { get; set; }
    
        public virtual ArchivoAdjunto ArchivoAdjunto { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
    }
}
