//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class test_linqsql1Entities : DbContext
    {
        public test_linqsql1Entities()
            : base("name=test_linqsql1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adjunto> Adjunto { get; set; }
        public DbSet<departamento1> departamento1 { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<into_sel> into_sel { get; set; }
        public DbSet<puesto1> puesto1 { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TicketArchivoAdjunto> TicketArchivoAdjunto { get; set; }
        public DbSet<user1> user1 { get; set; }
    
        public virtual ObjectResult<STEP_1_Result> STEP_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STEP_1_Result>("STEP_1");
        }
    
        public virtual ObjectResult<STEP_COLUMN_Result> STEP_COLUMN(string tabla)
        {
            var tablaParameter = tabla != null ?
                new ObjectParameter("tabla", tabla) :
                new ObjectParameter("tabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STEP_COLUMN_Result>("STEP_COLUMN", tablaParameter);
        }
    
        public virtual ObjectResult<string> STEP_TABLE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("STEP_TABLE");
        }
    
        public virtual int STEP_search(string tabla, string campo, string valor)
        {
            var tablaParameter = tabla != null ?
                new ObjectParameter("tabla", tabla) :
                new ObjectParameter("tabla", typeof(string));
    
            var campoParameter = campo != null ?
                new ObjectParameter("campo", campo) :
                new ObjectParameter("campo", typeof(string));
    
            var valorParameter = valor != null ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STEP_search", tablaParameter, campoParameter, valorParameter);
        }
    }
}
