//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrioridadPorSubcategoria
    {
        public PrioridadPorSubcategoria()
        {
            this.Problema = new HashSet<Problema>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int DetalleId { get; set; }
        public int SubcategoriaId { get; set; }
        public int PrioridadId { get; set; }
        public int TiempoMaximoAtencion { get; set; }
        public int TiempoMaximoSolucion { get; set; }
    
        public virtual Prioridad Prioridad { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
        public virtual ICollection<Problema> Problema { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
