//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prioridad
    {
        public Prioridad()
        {
            this.PrioridadPorSubcategoria = new HashSet<PrioridadPorSubcategoria>();
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int PrioridadId { get; set; }
        public string Descripcion { get; set; }
        public string ColorRgb { get; set; }
    
        public virtual ICollection<PrioridadPorSubcategoria> PrioridadPorSubcategoria { get; set; }
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
