//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.ServicioPorCliente = new HashSet<ServicioPorCliente>();
        }
    
        public int ServicioId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<ServicioPorCliente> ServicioPorCliente { get; set; }
    }
}
