//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioPorCliente
    {
        public ServicioPorCliente()
        {
            this.ServicioPorProblema = new HashSet<ServicioPorProblema>();
        }
    
        public int DetalleId { get; set; }
        public int ServicioId { get; set; }
        public int ClienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual ICollection<ServicioPorProblema> ServicioPorProblema { get; set; }
    }
}
