//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int SolicitudId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Asunto { get; set; }
        public string Descripcion { get; set; }
        public byte[] Adjunto { get; set; }
        public Nullable<int> UsuarioAsignadoId { get; set; }
        public byte Estado { get; set; }
        public Nullable<System.DateTime> FechaAsignado { get; set; }
        public Nullable<System.DateTime> FechaAbierto { get; set; }
        public Nullable<System.DateTime> FechaCerrado { get; set; }
        public Nullable<System.DateTime> FechaPausado { get; set; }
        public Nullable<decimal> MinutosPausado { get; set; }
        public string Explicacion { get; set; }
        public Nullable<int> PrioridadId { get; set; }
        public Nullable<System.DateTime> FechaCulminacion { get; set; }
        public Nullable<int> UsuarioAsignadorId { get; set; }
    
        public virtual Prioridad Prioridad { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
    }
}
