//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategoria
    {
        public Subcategoria()
        {
            this.FormatoPorCliente = new HashSet<FormatoPorCliente>();
            this.PrioridadPorSubcategoria = new HashSet<PrioridadPorSubcategoria>();
            this.Problema = new HashSet<Problema>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int SubcategoriaId { get; set; }
        public int CategoriaId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<FormatoPorCliente> FormatoPorCliente { get; set; }
        public virtual ICollection<PrioridadPorSubcategoria> PrioridadPorSubcategoria { get; set; }
        public virtual ICollection<Problema> Problema { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
