//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketArchivoAdjunto = new HashSet<TicketArchivoAdjunto>();
        }
    
        public int TicketId { get; set; }
        public int SubcategoriaId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> PrioridadSubcategoriaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Asunto { get; set; }
        public string Descripcion { get; set; }
        public byte[] Adjunto { get; set; }
        public Nullable<int> UsuarioAsignadoId { get; set; }
        public byte Estado { get; set; }
        public Nullable<System.DateTime> FechaAsignado { get; set; }
        public Nullable<System.DateTime> FechaAbierto { get; set; }
        public Nullable<System.DateTime> FechaCerrado { get; set; }
        public Nullable<System.DateTime> FechaPausado { get; set; }
        public Nullable<decimal> MinutosPausado { get; set; }
        public string Explicacion { get; set; }
        public Nullable<bool> Edu { get; set; }
        public Nullable<int> UsuarioAsignadorId { get; set; }
    
        public virtual PrioridadPorSubcategoria PrioridadPorSubcategoria { get; set; }
        public virtual Subcategoria Subcategoria { get; set; }
        public virtual Ticket Ticket1 { get; set; }
        public virtual Ticket Ticket2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<TicketArchivoAdjunto> TicketArchivoAdjunto { get; set; }
    }
}
