//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        public int TransferenciaId { get; set; }
        public int TicketId { get; set; }
        public int UsuarioDeId { get; set; }
        public int UsuarioParaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte TipoTicket { get; set; }
    }
}
