//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Mensaje = new HashSet<Mensaje>();
            this.Problema = new HashSet<Problema>();
            this.RecursoPorProblema = new HashSet<RecursoPorProblema>();
            this.Solicitud = new HashSet<Solicitud>();
            this.Solicitud1 = new HashSet<Solicitud>();
            this.Solicitud2 = new HashSet<Solicitud>();
            this.Ticket = new HashSet<Ticket>();
            this.Ticket1 = new HashSet<Ticket>();
            this.Ticket2 = new HashSet<Ticket>();
            this.webpages_UsersInRoles = new HashSet<webpages_UsersInRoles>();
            this.Valija = new HashSet<Valija>();
            this.Valija1 = new HashSet<Valija>();
        }
    
        public int UsuarioId { get; set; }
        public string Email { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string Telefono { get; set; }
        public int ClienteId { get; set; }
        public string InformacionGeneral { get; set; }
        public Nullable<bool> AccesoDem { get; set; }
        public Nullable<bool> AccesoValija { get; set; }
        public Nullable<int> UsuarioSD { get; set; }
        public Nullable<System.DateTime> UltimoAcceso { get; set; }
        public Nullable<int> CargoId { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Mensaje> Mensaje { get; set; }
        public virtual ICollection<Problema> Problema { get; set; }
        public virtual ICollection<RecursoPorProblema> RecursoPorProblema { get; set; }
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        public virtual ICollection<Solicitud> Solicitud1 { get; set; }
        public virtual ICollection<Solicitud> Solicitud2 { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<Ticket> Ticket1 { get; set; }
        public virtual ICollection<Ticket> Ticket2 { get; set; }
        public virtual webpages_Membership webpages_Membership { get; set; }
        public virtual ICollection<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public virtual ICollection<Valija> Valija { get; set; }
        public virtual ICollection<Valija> Valija1 { get; set; }
    }
}
