//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace busqueda_todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSolicitudes
    {
        public int SolicitudId { get; set; }
        public string Cliente { get; set; }
        public string Asunto { get; set; }
        public string Solicitante { get; set; }
        public string Administrador { get; set; }
        public string Prioridad { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> DiasTranscurridos { get; set; }
        public string FinAproximado { get; set; }
        public Nullable<System.DateTime> FechaAbierto { get; set; }
        public Nullable<System.DateTime> FechaPausado { get; set; }
        public Nullable<System.DateTime> FechaCerrado { get; set; }
        public byte Estado { get; set; }
        public int ClienteId { get; set; }
        public Nullable<int> AdministradorId { get; set; }
        public Nullable<int> PrioridadId { get; set; }
        public string ColorRgb { get; set; }
        public int SolicitanteId { get; set; }
        public string SolicitanteEmail { get; set; }
        public string AdministradorEmail { get; set; }
        public string Descripcion { get; set; }
        public string Explicacion { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaCulminacion { get; set; }
        public string Asignador { get; set; }
    }
}
